import {
	CCW_HANDPATH,
	CLOCK,
	CLOCKWISE,
	COUNTER,
	COUNTER_CLOCKWISE,
	CW_HANDPATH,
	EAST,
	IN,
	NO_ROT,
	NORTH,
	NORTHEAST,
	NORTHWEST,
	OUT,
	SOUTH,
	SOUTHEAST,
	SOUTHWEST,
	WEST
} from '$lib/types/Constants';
import type {
	LocationOverrideMap,
	OrientationMap,
	PropRotDirMap,
	RotationDirectionMap
} from './arrowRotationTypes';

export const PRO_ROTATION_MAP: PropRotDirMap = {
	[CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 45,
		[SOUTH]: 135,
		[WEST]: 225,
		[NORTHEAST]: 0,
		[SOUTHEAST]: 90,
		[SOUTHWEST]: 180,
		[NORTHWEST]: 270
	},
	[COUNTER_CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 225,
		[SOUTH]: 135,
		[WEST]: 45,
		[NORTHEAST]: 270,
		[SOUTHEAST]: 180,
		[SOUTHWEST]: 90,
		[NORTHWEST]: 0
	},
	[NO_ROT]: {}
};

export const ANTI_REGULAR_MAP: PropRotDirMap = {
	[CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 225,
		[SOUTH]: 135,
		[WEST]: 45,
		[NORTHEAST]: 270,
		[SOUTHEAST]: 180,
		[SOUTHWEST]: 90,
		[NORTHWEST]: 0
	},
	[COUNTER_CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 45,
		[SOUTH]: 135,
		[WEST]: 225,
		[NORTHEAST]: 0,
		[SOUTHEAST]: 90,
		[SOUTHWEST]: 180,
		[NORTHWEST]: 270
	},
	[NO_ROT]: {}
};

export const ANTI_ALT_MAP: PropRotDirMap = {
	[CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 225,
		[SOUTH]: 135,
		[WEST]: 45,
		[NORTHEAST]: 270,
		[SOUTHEAST]: 180,
		[SOUTHWEST]: 90,
		[NORTHWEST]: 360
	},
	[COUNTER_CLOCKWISE]: {
		[NORTH]: 315,
		[EAST]: 45,
		[SOUTH]: 135,
		[WEST]: 225,
		[NORTHEAST]: 360,
		[SOUTHEAST]: 90,
		[SOUTHWEST]: 180,
		[NORTHWEST]: 270
	},
	[NO_ROT]: {}
};

export const FLOAT_DIRECTION_MAP: { [key: string]: RotationDirectionMap } = {
	[CW_HANDPATH]: {
		[NORTH]: 315,
		[EAST]: 45,
		[SOUTH]: 135,
		[WEST]: 225,
		[NORTHEAST]: 0,
		[SOUTHEAST]: 90,
		[SOUTHWEST]: 180,
		[NORTHWEST]: 270
	},
	[CCW_HANDPATH]: {
		[NORTH]: 135,
		[EAST]: 225,
		[SOUTH]: 315,
		[WEST]: 45,
		[NORTHEAST]: 180,
		[SOUTHEAST]: 270,
		[SOUTHWEST]: 0,
		[NORTHWEST]: 90
	}
};

export const DASH_NO_ROTATION_MAP: { [key: string]: number } = {
	[`${NORTH}-${SOUTH}`]: 90,
	[`${EAST}-${WEST}`]: 180,
	[`${SOUTH}-${NORTH}`]: 270,
	[`${WEST}-${EAST}`]: 0,
	[`${SOUTHEAST}-${NORTHWEST}`]: 225,
	[`${SOUTHWEST}-${NORTHEAST}`]: 315,
	[`${NORTHWEST}-${SOUTHEAST}`]: 45,
	[`${NORTHEAST}-${SOUTHWEST}`]: 135
};

export const DASH_ORIENTATION_MAP: OrientationMap = {
	[IN]: {
		[CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 90,
			[SOUTH]: 180,
			[WEST]: 270,
			[NORTHEAST]: 45,
			[SOUTHEAST]: 135,
			[SOUTHWEST]: 225,
			[NORTHWEST]: 315
		},
		[COUNTER_CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 270,
			[SOUTH]: 180,
			[WEST]: 90,
			[NORTHEAST]: 315,
			[SOUTHEAST]: 225,
			[SOUTHWEST]: 135,
			[NORTHWEST]: 45
		},
		[NO_ROT]: {}
	},
	[OUT]: {
		[CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 90,
			[SOUTH]: 180,
			[WEST]: 270,
			[NORTHEAST]: 45,
			[SOUTHEAST]: 135,
			[SOUTHWEST]: 225,
			[NORTHWEST]: 315
		},
		[COUNTER_CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 270,
			[SOUTH]: 180,
			[WEST]: 90,
			[NORTHEAST]: 315,
			[SOUTHEAST]: 225,
			[SOUTHWEST]: 135,
			[NORTHWEST]: 45
		},
		[NO_ROT]: {}
	},
	[CLOCK]: {
		[CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 90,
			[SOUTH]: 180,
			[WEST]: 270,
			[NORTHEAST]: 45,
			[SOUTHEAST]: 135,
			[SOUTHWEST]: 225,
			[NORTHWEST]: 315
		},
		[COUNTER_CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 270,
			[SOUTH]: 180,
			[WEST]: 90,
			[NORTHEAST]: 315,
			[SOUTHEAST]: 225,
			[SOUTHWEST]: 135,
			[NORTHWEST]: 45
		},
		[NO_ROT]: {}
	},
	[COUNTER]: {
		[CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 90,
			[SOUTH]: 180,
			[WEST]: 270,
			[NORTHEAST]: 45,
			[SOUTHEAST]: 135,
			[SOUTHWEST]: 225,
			[NORTHWEST]: 315
		},
		[COUNTER_CLOCKWISE]: {
			[NORTH]: 0,
			[EAST]: 270,
			[SOUTH]: 180,
			[WEST]: 90,
			[NORTHEAST]: 315,
			[SOUTHEAST]: 225,
			[SOUTHWEST]: 135,
			[NORTHWEST]: 45
		},
		[NO_ROT]: {}
	}
};

export const CW_DASH_ANGLE_OVERRIDE_MAP: RotationDirectionMap = {
	[NORTH]: 270,
	[EAST]: 0,
	[SOUTH]: 90,
	[WEST]: 180,
	[NORTHEAST]: 315,
	[SOUTHEAST]: 45,
	[SOUTHWEST]: 135,
	[NORTHWEST]: 225
};

export const CCW_DASH_ANGLE_OVERRIDE_MAP: RotationDirectionMap = {
	[NORTH]: 270,
	[EAST]: 180,
	[SOUTH]: 90,
	[WEST]: 0,
	[NORTHEAST]: 225,
	[SOUTHEAST]: 135,
	[SOUTHWEST]: 45,
	[NORTHWEST]: 315
};

export const RADIAL_STATIC_DIRECTION_MAP: PropRotDirMap = {
	[CLOCKWISE]: {
		[NORTH]: 0,
		[EAST]: 90,
		[SOUTH]: 180,
		[WEST]: 270,
		[NORTHEAST]: 45,
		[SOUTHEAST]: 135,
		[SOUTHWEST]: 225,
		[NORTHWEST]: 315
	},
	[COUNTER_CLOCKWISE]: {
		[NORTH]: 0,
		[EAST]: 270,
		[SOUTH]: 180,
		[WEST]: 90,
		[NORTHEAST]: 315,
		[SOUTHEAST]: 225,
		[SOUTHWEST]: 135,
		[NORTHWEST]: 45
	},
	[NO_ROT]: {}
};

export const NONRADIAL_STATIC_DIRECTION_MAP: PropRotDirMap = {
	[CLOCKWISE]: {
		[NORTH]: 180,
		[EAST]: 270,
		[SOUTH]: 0,
		[WEST]: 90,
		[NORTHEAST]: 225,
		[SOUTHEAST]: 315,
		[SOUTHWEST]: 45,
		[NORTHWEST]: 135
	},
	[COUNTER_CLOCKWISE]: {
		[NORTH]: 180,
		[EAST]: 90,
		[SOUTH]: 0,
		[WEST]: 270,
		[NORTHEAST]: 135,
		[SOUTHEAST]: 45,
		[SOUTHWEST]: 315,
		[NORTHWEST]: 225
	},
	[NO_ROT]: {}
};

export const STATIC_FROM_RADIAL_ANGLE_OVERRIDE_MAP: LocationOverrideMap = {
	[NORTH]: 180,
	[EAST]: { [CLOCKWISE]: 270, [COUNTER_CLOCKWISE]: 90, [NO_ROT]: 0 },
	[SOUTH]: 0,
	[WEST]: { [CLOCKWISE]: 90, [COUNTER_CLOCKWISE]: 270, [NO_ROT]: 0 },
	[NORTHEAST]: { [CLOCKWISE]: 225, [COUNTER_CLOCKWISE]: 135, [NO_ROT]: 0 },
	[SOUTHEAST]: { [CLOCKWISE]: 315, [COUNTER_CLOCKWISE]: 45, [NO_ROT]: 0 },
	[SOUTHWEST]: { [CLOCKWISE]: 45, [COUNTER_CLOCKWISE]: 315, [NO_ROT]: 0 },
	[NORTHWEST]: { [CLOCKWISE]: 135, [COUNTER_CLOCKWISE]: 225, [NO_ROT]: 0 }
};

export const STATIC_FROM_NONRADIAL_ANGLE_OVERRIDE_MAP: LocationOverrideMap = {
	[NORTH]: 0,
	[EAST]: { [CLOCKWISE]: 90, [COUNTER_CLOCKWISE]: 270, [NO_ROT]: 0 },
	[SOUTH]: 180,
	[WEST]: { [CLOCKWISE]: 270, [COUNTER_CLOCKWISE]: 90, [NO_ROT]: 0 },
	[NORTHEAST]: { [CLOCKWISE]: 45, [COUNTER_CLOCKWISE]: 315, [NO_ROT]: 0 },
	[SOUTHEAST]: { [CLOCKWISE]: 135, [COUNTER_CLOCKWISE]: 225, [NO_ROT]: 0 },
	[SOUTHWEST]: { [CLOCKWISE]: 225, [COUNTER_CLOCKWISE]: 135, [NO_ROT]: 0 },
	[NORTHWEST]: { [CLOCKWISE]: 315, [COUNTER_CLOCKWISE]: 45, [NO_ROT]: 0 }
};
