<!-- src/lib/components/SequenceWorkbench/SequenceBeatFrame/StartPosBeat.svelte -->
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import Beat from './Beat.svelte';
	import type { BeatData } from './BeatData';
	import { defaultPictographData } from '$lib/components/Pictograph/utils/defaultPictographData';
	import { selectedStartPos } from '$lib/stores/sequence/selectionStore';
	import { pictographStore } from '$lib/state/stores/pictograph/pictograph.store';
	import { writable } from 'svelte/store';
	import type { PictographData } from '$lib/types/PictographData';
	import { updateDevTools } from '$lib/utils/devToolsUpdater';

	export let beatData: BeatData;
	export let onClick: () => void;

	// Create a local store for the pictograph data for the Pictograph component
	const pictographDataStore = writable(beatData.pictographData);

	// Helper function to safely copy pictograph data without circular references
	function safeCopyPictographData(data: PictographData): PictographData {
		// Create a new object with only the properties we need
		const safeCopy: PictographData = {
			letter: data.letter,
			startPos: data.startPos,
			endPos: data.endPos,
			timing: data.timing,
			direction: data.direction,
			gridMode: data.gridMode,
			grid: data.grid,

			// Copy motion data safely
			redMotionData: data.redMotionData
				? {
						id: data.redMotionData.id,
						handRotDir: data.redMotionData.handRotDir,
						color: data.redMotionData.color,
						leadState: data.redMotionData.leadState,
						motionType: data.redMotionData.motionType,
						startLoc: data.redMotionData.startLoc,
						endLoc: data.redMotionData.endLoc,
						startOri: data.redMotionData.startOri,
						endOri: data.redMotionData.endOri,
						propRotDir: data.redMotionData.propRotDir,
						turns: data.redMotionData.turns,
						prefloatMotionType: data.redMotionData.prefloatMotionType,
						prefloatPropRotDir: data.redMotionData.prefloatPropRotDir
					}
				: null,

			blueMotionData: data.blueMotionData
				? {
						id: data.blueMotionData.id,
						handRotDir: data.blueMotionData.handRotDir,
						color: data.blueMotionData.color,
						leadState: data.blueMotionData.leadState,
						motionType: data.blueMotionData.motionType,
						startLoc: data.blueMotionData.startLoc,
						endLoc: data.blueMotionData.endLoc,
						startOri: data.blueMotionData.startOri,
						endOri: data.blueMotionData.endOri,
						propRotDir: data.blueMotionData.propRotDir,
						turns: data.blueMotionData.turns,
						prefloatMotionType: data.blueMotionData.prefloatMotionType,
						prefloatPropRotDir: data.blueMotionData.prefloatPropRotDir
					}
				: null,

			// These will be generated by the Pictograph component
			redPropData: null,
			bluePropData: null,
			redArrowData: null,
			blueArrowData: null,
			gridData: null,

			// Copy arrays safely
			motions: [],
			redMotion: null,
			blueMotion: null,
			props: []
		};

		return safeCopy;
	}

	// Make sure the pictographDataStore is updated when beatData changes
	$: if (beatData && beatData.pictographData) {
		const safeCopy = safeCopyPictographData(beatData.pictographData);
		pictographDataStore.set(safeCopy);
	}

	// Subscribe to the selectedStartPos store directly from the global store
	const unsubscribeStartPos = selectedStartPos.subscribe((startPos) => {
		if (startPos) {
			// Create a deep copy to avoid reference issues
			const startPosCopy = JSON.parse(JSON.stringify(startPos));

			// Update the local pictograph data when the start position changes
			pictographDataStore.set(startPosCopy);

			// Also update the new pictographStore
			pictographStore.setData(startPosCopy);

			console.log('StartPosBeat: Updated pictographDataStore with startPos:', startPosCopy);

			// Also update the beat data directly
			beatData = {
				...beatData,
				pictographData: startPosCopy,
				filled: true
			};
		} else {
			// If no start position is set, use default data
			pictographDataStore.set(defaultPictographData);

			// Also update the new pictographStore
			pictographStore.setData(defaultPictographData);

			// Update the beat data accordingly
			beatData = {
				...beatData,
				pictographData: defaultPictographData,
				filled: false
			};
		}
	});

	// Listen for the custom event as an alternative way to receive updates
	onMount(() => {
		const handleStartPosSelectedEvent = (event: CustomEvent) => {
			if (event.detail?.startPosition) {
				// Create a deep copy to avoid reference issues
				const newStartPos = JSON.parse(JSON.stringify(event.detail.startPosition));

				console.log('StartPosBeat: Received start-position-selected event with data:', newStartPos);

				// Update the pictograph store with the new data
				pictographDataStore.set(newStartPos);

				// Also update the new pictographStore
				pictographStore.setData(newStartPos);

				// Update the beat data
				beatData = {
					...beatData,
					pictographData: newStartPos,
					filled: true
				};
			}
		};

		// Add event listener
		document.addEventListener(
			'start-position-selected',
			handleStartPosSelectedEvent as EventListener
		);

		return () => {
			// Clean up event listener
			document.removeEventListener(
				'start-position-selected',
				handleStartPosSelectedEvent as EventListener
			);
		};
	});

	// Clean up subscription when component is destroyed
	onDestroy(() => {
		unsubscribeStartPos();
	});

	// Handle clicks at this level to prevent multiple event handlers
	function handleContainerClick(event: MouseEvent) {
		// Only handle clicks directly on the container, not on children
		if (event.target === event.currentTarget) {
			onClick();

			// Update dev tools after click
			updateDevTools();
		}
	}
</script>

<button class="start-pos-beat" on:click={handleContainerClick} type="button">
	<Beat beat={beatData} {onClick} isStartPosition={true} />
</button>

<style>
	.start-pos-beat {
		position: relative;
		width: 100%;
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		border-radius: 8px;
		background-color: transparent;
		border: none;
		padding: 0; /* Remove default button padding */
		margin: 0; /* Remove any margin */
		box-sizing: border-box; /* Ensure padding is included in width/height */
	}
</style>
